// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projektgrupp4.Contexts;

#nullable disable

namespace Projektgrupp4.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AddressEntityUserEntity", b =>
                {
                    b.Property<Guid>("UserAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UsersId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserAddressId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("AddressEntityUserEntity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Projektgrupp4.Models.Entities.AddressEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostalCode")
                        .HasColumnType("int");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StreetNumber")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Adresses");
                });

            modelBuilder.Entity("Projektgrupp4.Models.Entities.CategoryEntity", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Men"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Women"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Kids"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Accessories"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Shoes"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Dresses"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Pants"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Bestsellers"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Featured"
                        });
                });

            modelBuilder.Entity("Projektgrupp4.Models.Entities.ColorEntity", b =>
                {
                    b.Property<int>("ColorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColorId"));

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ColorId");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            ColorId = 1,
                            ColorName = "White"
                        },
                        new
                        {
                            ColorId = 2,
                            ColorName = "Black"
                        },
                        new
                        {
                            ColorId = 3,
                            ColorName = "Red"
                        },
                        new
                        {
                            ColorId = 4,
                            ColorName = "Green"
                        },
                        new
                        {
                            ColorId = 5,
                            ColorName = "Blue"
                        },
                        new
                        {
                            ColorId = 6,
                            ColorName = "Beige"
                        },
                        new
                        {
                            ColorId = 7,
                            ColorName = "LightBlue"
                        },
                        new
                        {
                            ColorId = 8,
                            ColorName = "DarkBlue"
                        },
                        new
                        {
                            ColorId = 9,
                            ColorName = "Orange"
                        },
                        new
                        {
                            ColorId = 10,
                            ColorName = "Yellow"
                        },
                        new
                        {
                            ColorId = 11,
                            ColorName = "Purple"
                        });
                });

            modelBuilder.Entity("Projektgrupp4.Models.Entities.ProductCategoriesEntity", b =>
                {
                    b.Property<int>("ProductCategoryRowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductCategoryRowId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("ProductCategoryRowId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("Projektgrupp4.Models.Entities.ProductEntity", b =>
                {
                    b.Property<int>("ArticleNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticleNumber"));

                    b.Property<string>("ProductDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ProductOfferPrice")
                        .HasColumnType("money");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("money");

                    b.Property<bool>("ProductPriceOrOffer")
                        .HasColumnType("bit");

                    b.Property<string>("ProductTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArticleNumber");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ArticleNumber = 1,
                            ProductDescription = "Amet amet Lorem eu consectetur in deserunt nostrud dolor culpa ad sint amet. Nostrud deserunt consectetur culpa minim mollit veniam aliquip pariatur exercitation ullamco ea voluptate et. Pariatur ipsum mollit magna proident nisi ipsum.",
                            ProductImageUrl = "#",
                            ProductOfferPrice = 0m,
                            ProductPrice = 29.80m,
                            ProductPriceOrOffer = false,
                            ProductTitle = "Black sneakers"
                        },
                        new
                        {
                            ArticleNumber = 2,
                            ProductDescription = "Amet amet Lorem eu consectetur in deserunt nostrud dolor culpa ad sint amet. Nostrud deserunt consectetur culpa minim mollit veniam aliquip pariatur exercitation ullamco ea voluptate et. Pariatur ipsum mollit magna proident nisi ipsum.",
                            ProductImageUrl = "#",
                            ProductOfferPrice = 15.98m,
                            ProductPrice = 36.00m,
                            ProductPriceOrOffer = true,
                            ProductTitle = "Summer dress"
                        },
                        new
                        {
                            ArticleNumber = 3,
                            ProductDescription = "Amet amet Lorem eu consectetur in deserunt nostrud dolor culpa ad sint amet. Nostrud deserunt consectetur culpa minim mollit veniam aliquip pariatur exercitation ullamco ea voluptate et. Pariatur ipsum mollit magna proident nisi ipsum.",
                            ProductImageUrl = "#",
                            ProductOfferPrice = 30.00m,
                            ProductPrice = 38.00m,
                            ProductPriceOrOffer = true,
                            ProductTitle = "Shoulder bag"
                        },
                        new
                        {
                            ArticleNumber = 4,
                            ProductDescription = "Amet amet Lorem eu consectetur in deserunt nostrud dolor culpa ad sint amet. Nostrud deserunt consectetur culpa minim mollit veniam aliquip pariatur exercitation ullamco ea voluptate et. Pariatur ipsum mollit magna proident nisi ipsum.",
                            ProductImageUrl = "#",
                            ProductOfferPrice = 0m,
                            ProductPrice = 54.96m,
                            ProductPriceOrOffer = false,
                            ProductTitle = "Denim shorts"
                        },
                        new
                        {
                            ArticleNumber = 5,
                            ProductDescription = "Amet amet Lorem eu consectetur in deserunt nostrud dolor culpa ad sint amet. Nostrud deserunt consectetur culpa minim mollit veniam aliquip pariatur exercitation ullamco ea voluptate et. Pariatur ipsum mollit magna proident nisi ipsum.",
                            ProductImageUrl = "#",
                            ProductOfferPrice = 0m,
                            ProductPrice = 31.78m,
                            ProductPriceOrOffer = false,
                            ProductTitle = "Summer pants"
                        },
                        new
                        {
                            ArticleNumber = 6,
                            ProductDescription = "Amet amet Lorem eu consectetur in deserunt nostrud dolor culpa ad sint amet. Nostrud deserunt consectetur culpa minim mollit veniam aliquip pariatur exercitation ullamco ea voluptate et. Pariatur ipsum mollit magna proident nisi ipsum.",
                            ProductImageUrl = "#",
                            ProductOfferPrice = 0m,
                            ProductPrice = 6.93m,
                            ProductPriceOrOffer = false,
                            ProductTitle = "Warm hat"
                        },
                        new
                        {
                            ArticleNumber = 7,
                            ProductDescription = "Amet amet Lorem eu consectetur in deserunt nostrud dolor culpa ad sint amet. Nostrud deserunt consectetur culpa minim mollit veniam aliquip pariatur exercitation ullamco ea voluptate et. Pariatur ipsum mollit magna proident nisi ipsum.",
                            ProductImageUrl = "#",
                            ProductOfferPrice = 0m,
                            ProductPrice = 24.95m,
                            ProductPriceOrOffer = false,
                            ProductTitle = "Hand bag"
                        },
                        new
                        {
                            ArticleNumber = 8,
                            ProductDescription = "Amet amet Lorem eu consectetur in deserunt nostrud dolor culpa ad sint amet. Nostrud deserunt consectetur culpa minim mollit veniam aliquip pariatur exercitation ullamco ea voluptate et. Pariatur ipsum mollit magna proident nisi ipsum.",
                            ProductImageUrl = "#",
                            ProductOfferPrice = 0m,
                            ProductPrice = 12.95m,
                            ProductPriceOrOffer = false,
                            ProductTitle = "T-shirt"
                        },
                        new
                        {
                            ArticleNumber = 9,
                            ProductDescription = "Amet amet Lorem eu consectetur in deserunt nostrud dolor culpa ad sint amet. Nostrud deserunt consectetur culpa minim mollit veniam aliquip pariatur exercitation ullamco ea voluptate et. Pariatur ipsum mollit magna proident nisi ipsum.",
                            ProductImageUrl = "#",
                            ProductOfferPrice = 0m,
                            ProductPrice = 22.87m,
                            ProductPriceOrOffer = false,
                            ProductTitle = "Purple sneakers"
                        },
                        new
                        {
                            ArticleNumber = 10,
                            ProductDescription = "Amet amet Lorem eu consectetur in deserunt nostrud dolor culpa ad sint amet. Nostrud deserunt consectetur culpa minim mollit veniam aliquip pariatur exercitation ullamco ea voluptate et. Pariatur ipsum mollit magna proident nisi ipsum.",
                            ProductImageUrl = "#",
                            ProductOfferPrice = 0m,
                            ProductPrice = 54.96m,
                            ProductPriceOrOffer = false,
                            ProductTitle = "Denim shorts"
                        });
                });

            modelBuilder.Entity("Projektgrupp4.Models.Entities.ProductItemEntity", b =>
                {
                    b.Property<int>("ProductEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductEntryId"));

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SizeId")
                        .HasColumnType("int");

                    b.HasKey("ProductEntryId");

                    b.HasIndex("ColorId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SizeId");

                    b.ToTable("ProductItem");

                    b.HasData(
                        new
                        {
                            ProductEntryId = 1,
                            ColorId = 2,
                            ProductId = 1,
                            SizeId = 7
                        },
                        new
                        {
                            ProductEntryId = 2,
                            ColorId = 2,
                            ProductId = 1,
                            SizeId = 8
                        },
                        new
                        {
                            ProductEntryId = 3,
                            ColorId = 2,
                            ProductId = 1,
                            SizeId = 9
                        },
                        new
                        {
                            ProductEntryId = 4,
                            ColorId = 2,
                            ProductId = 1,
                            SizeId = 10
                        },
                        new
                        {
                            ProductEntryId = 5,
                            ColorId = 2,
                            ProductId = 1,
                            SizeId = 11
                        },
                        new
                        {
                            ProductEntryId = 6,
                            ColorId = 2,
                            ProductId = 1,
                            SizeId = 12
                        },
                        new
                        {
                            ProductEntryId = 7,
                            ColorId = 2,
                            ProductId = 1,
                            SizeId = 13
                        },
                        new
                        {
                            ProductEntryId = 8,
                            ColorId = 2,
                            ProductId = 1,
                            SizeId = 14
                        },
                        new
                        {
                            ProductEntryId = 9,
                            ColorId = 1,
                            ProductId = 2,
                            SizeId = 1
                        },
                        new
                        {
                            ProductEntryId = 10,
                            ColorId = 1,
                            ProductId = 2,
                            SizeId = 2
                        },
                        new
                        {
                            ProductEntryId = 11,
                            ColorId = 1,
                            ProductId = 2,
                            SizeId = 3
                        },
                        new
                        {
                            ProductEntryId = 12,
                            ColorId = 1,
                            ProductId = 2,
                            SizeId = 4
                        },
                        new
                        {
                            ProductEntryId = 13,
                            ColorId = 1,
                            ProductId = 2,
                            SizeId = 5
                        },
                        new
                        {
                            ProductEntryId = 14,
                            ColorId = 1,
                            ProductId = 2,
                            SizeId = 6
                        },
                        new
                        {
                            ProductEntryId = 15,
                            ColorId = 6,
                            ProductId = 2,
                            SizeId = 1
                        },
                        new
                        {
                            ProductEntryId = 16,
                            ColorId = 6,
                            ProductId = 2,
                            SizeId = 2
                        },
                        new
                        {
                            ProductEntryId = 17,
                            ColorId = 6,
                            ProductId = 2,
                            SizeId = 3
                        },
                        new
                        {
                            ProductEntryId = 18,
                            ColorId = 6,
                            ProductId = 2,
                            SizeId = 4
                        },
                        new
                        {
                            ProductEntryId = 19,
                            ColorId = 6,
                            ProductId = 2,
                            SizeId = 5
                        },
                        new
                        {
                            ProductEntryId = 20,
                            ColorId = 6,
                            ProductId = 2,
                            SizeId = 6
                        },
                        new
                        {
                            ProductEntryId = 21,
                            ColorId = 7,
                            ProductId = 2,
                            SizeId = 1
                        },
                        new
                        {
                            ProductEntryId = 22,
                            ColorId = 7,
                            ProductId = 2,
                            SizeId = 2
                        },
                        new
                        {
                            ProductEntryId = 23,
                            ColorId = 7,
                            ProductId = 2,
                            SizeId = 3
                        },
                        new
                        {
                            ProductEntryId = 24,
                            ColorId = 7,
                            ProductId = 2,
                            SizeId = 4
                        },
                        new
                        {
                            ProductEntryId = 25,
                            ColorId = 7,
                            ProductId = 2,
                            SizeId = 5
                        },
                        new
                        {
                            ProductEntryId = 26,
                            ColorId = 7,
                            ProductId = 2,
                            SizeId = 6
                        },
                        new
                        {
                            ProductEntryId = 27,
                            ColorId = 10,
                            ProductId = 2,
                            SizeId = 1
                        },
                        new
                        {
                            ProductEntryId = 28,
                            ColorId = 10,
                            ProductId = 2,
                            SizeId = 2
                        },
                        new
                        {
                            ProductEntryId = 29,
                            ColorId = 10,
                            ProductId = 2,
                            SizeId = 3
                        },
                        new
                        {
                            ProductEntryId = 30,
                            ColorId = 10,
                            ProductId = 2,
                            SizeId = 4
                        },
                        new
                        {
                            ProductEntryId = 31,
                            ColorId = 10,
                            ProductId = 2,
                            SizeId = 5
                        },
                        new
                        {
                            ProductEntryId = 32,
                            ColorId = 10,
                            ProductId = 2,
                            SizeId = 6
                        },
                        new
                        {
                            ProductEntryId = 33,
                            ColorId = 7,
                            ProductId = 4,
                            SizeId = 1
                        },
                        new
                        {
                            ProductEntryId = 34,
                            ColorId = 7,
                            ProductId = 4,
                            SizeId = 2
                        },
                        new
                        {
                            ProductEntryId = 35,
                            ColorId = 7,
                            ProductId = 4,
                            SizeId = 3
                        },
                        new
                        {
                            ProductEntryId = 36,
                            ColorId = 7,
                            ProductId = 4,
                            SizeId = 4
                        },
                        new
                        {
                            ProductEntryId = 37,
                            ColorId = 7,
                            ProductId = 4,
                            SizeId = 5
                        },
                        new
                        {
                            ProductEntryId = 38,
                            ColorId = 7,
                            ProductId = 4,
                            SizeId = 6
                        },
                        new
                        {
                            ProductEntryId = 39,
                            ColorId = 8,
                            ProductId = 4,
                            SizeId = 1
                        },
                        new
                        {
                            ProductEntryId = 40,
                            ColorId = 8,
                            ProductId = 4,
                            SizeId = 2
                        },
                        new
                        {
                            ProductEntryId = 41,
                            ColorId = 8,
                            ProductId = 4,
                            SizeId = 3
                        },
                        new
                        {
                            ProductEntryId = 42,
                            ColorId = 8,
                            ProductId = 4,
                            SizeId = 4
                        },
                        new
                        {
                            ProductEntryId = 43,
                            ColorId = 8,
                            ProductId = 4,
                            SizeId = 5
                        },
                        new
                        {
                            ProductEntryId = 44,
                            ColorId = 8,
                            ProductId = 4,
                            SizeId = 6
                        },
                        new
                        {
                            ProductEntryId = 45,
                            ColorId = 2,
                            ProductId = 4,
                            SizeId = 1
                        },
                        new
                        {
                            ProductEntryId = 46,
                            ColorId = 2,
                            ProductId = 4,
                            SizeId = 2
                        },
                        new
                        {
                            ProductEntryId = 47,
                            ColorId = 2,
                            ProductId = 4,
                            SizeId = 3
                        },
                        new
                        {
                            ProductEntryId = 48,
                            ColorId = 2,
                            ProductId = 4,
                            SizeId = 4
                        },
                        new
                        {
                            ProductEntryId = 49,
                            ColorId = 2,
                            ProductId = 4,
                            SizeId = 5
                        },
                        new
                        {
                            ProductEntryId = 50,
                            ColorId = 2,
                            ProductId = 4,
                            SizeId = 6
                        },
                        new
                        {
                            ProductEntryId = 51,
                            ColorId = 5,
                            ProductId = 4,
                            SizeId = 1
                        },
                        new
                        {
                            ProductEntryId = 52,
                            ColorId = 5,
                            ProductId = 4,
                            SizeId = 2
                        },
                        new
                        {
                            ProductEntryId = 53,
                            ColorId = 5,
                            ProductId = 4,
                            SizeId = 3
                        },
                        new
                        {
                            ProductEntryId = 54,
                            ColorId = 5,
                            ProductId = 4,
                            SizeId = 4
                        },
                        new
                        {
                            ProductEntryId = 55,
                            ColorId = 5,
                            ProductId = 4,
                            SizeId = 5
                        },
                        new
                        {
                            ProductEntryId = 56,
                            ColorId = 5,
                            ProductId = 4,
                            SizeId = 6
                        },
                        new
                        {
                            ProductEntryId = 57,
                            ColorId = 7,
                            ProductId = 5,
                            SizeId = 1
                        },
                        new
                        {
                            ProductEntryId = 58,
                            ColorId = 7,
                            ProductId = 5,
                            SizeId = 2
                        },
                        new
                        {
                            ProductEntryId = 59,
                            ColorId = 7,
                            ProductId = 5,
                            SizeId = 3
                        },
                        new
                        {
                            ProductEntryId = 60,
                            ColorId = 7,
                            ProductId = 5,
                            SizeId = 4
                        },
                        new
                        {
                            ProductEntryId = 61,
                            ColorId = 7,
                            ProductId = 5,
                            SizeId = 5
                        },
                        new
                        {
                            ProductEntryId = 62,
                            ColorId = 7,
                            ProductId = 5,
                            SizeId = 6
                        },
                        new
                        {
                            ProductEntryId = 63,
                            ColorId = 1,
                            ProductId = 5,
                            SizeId = 1
                        },
                        new
                        {
                            ProductEntryId = 64,
                            ColorId = 1,
                            ProductId = 5,
                            SizeId = 2
                        },
                        new
                        {
                            ProductEntryId = 65,
                            ColorId = 1,
                            ProductId = 5,
                            SizeId = 3
                        },
                        new
                        {
                            ProductEntryId = 66,
                            ColorId = 1,
                            ProductId = 5,
                            SizeId = 4
                        },
                        new
                        {
                            ProductEntryId = 67,
                            ColorId = 1,
                            ProductId = 5,
                            SizeId = 5
                        },
                        new
                        {
                            ProductEntryId = 68,
                            ColorId = 1,
                            ProductId = 5,
                            SizeId = 6
                        },
                        new
                        {
                            ProductEntryId = 69,
                            ColorId = 6,
                            ProductId = 5,
                            SizeId = 1
                        },
                        new
                        {
                            ProductEntryId = 70,
                            ColorId = 6,
                            ProductId = 5,
                            SizeId = 2
                        },
                        new
                        {
                            ProductEntryId = 71,
                            ColorId = 6,
                            ProductId = 5,
                            SizeId = 3
                        },
                        new
                        {
                            ProductEntryId = 72,
                            ColorId = 6,
                            ProductId = 5,
                            SizeId = 4
                        },
                        new
                        {
                            ProductEntryId = 73,
                            ColorId = 6,
                            ProductId = 5,
                            SizeId = 5
                        },
                        new
                        {
                            ProductEntryId = 74,
                            ColorId = 6,
                            ProductId = 5,
                            SizeId = 6
                        },
                        new
                        {
                            ProductEntryId = 75,
                            ColorId = 1,
                            ProductId = 8,
                            SizeId = 1
                        },
                        new
                        {
                            ProductEntryId = 76,
                            ColorId = 1,
                            ProductId = 8,
                            SizeId = 2
                        },
                        new
                        {
                            ProductEntryId = 77,
                            ColorId = 1,
                            ProductId = 8,
                            SizeId = 3
                        },
                        new
                        {
                            ProductEntryId = 78,
                            ColorId = 1,
                            ProductId = 8,
                            SizeId = 4
                        },
                        new
                        {
                            ProductEntryId = 79,
                            ColorId = 1,
                            ProductId = 8,
                            SizeId = 5
                        },
                        new
                        {
                            ProductEntryId = 80,
                            ColorId = 1,
                            ProductId = 8,
                            SizeId = 6
                        },
                        new
                        {
                            ProductEntryId = 81,
                            ColorId = 2,
                            ProductId = 8,
                            SizeId = 1
                        },
                        new
                        {
                            ProductEntryId = 82,
                            ColorId = 2,
                            ProductId = 8,
                            SizeId = 2
                        },
                        new
                        {
                            ProductEntryId = 83,
                            ColorId = 2,
                            ProductId = 8,
                            SizeId = 3
                        },
                        new
                        {
                            ProductEntryId = 84,
                            ColorId = 2,
                            ProductId = 8,
                            SizeId = 4
                        },
                        new
                        {
                            ProductEntryId = 85,
                            ColorId = 2,
                            ProductId = 8,
                            SizeId = 5
                        },
                        new
                        {
                            ProductEntryId = 86,
                            ColorId = 2,
                            ProductId = 8,
                            SizeId = 6
                        },
                        new
                        {
                            ProductEntryId = 87,
                            ColorId = 3,
                            ProductId = 8,
                            SizeId = 1
                        },
                        new
                        {
                            ProductEntryId = 88,
                            ColorId = 3,
                            ProductId = 8,
                            SizeId = 2
                        },
                        new
                        {
                            ProductEntryId = 89,
                            ColorId = 3,
                            ProductId = 8,
                            SizeId = 3
                        },
                        new
                        {
                            ProductEntryId = 90,
                            ColorId = 3,
                            ProductId = 8,
                            SizeId = 4
                        },
                        new
                        {
                            ProductEntryId = 91,
                            ColorId = 3,
                            ProductId = 8,
                            SizeId = 5
                        },
                        new
                        {
                            ProductEntryId = 92,
                            ColorId = 3,
                            ProductId = 8,
                            SizeId = 6
                        },
                        new
                        {
                            ProductEntryId = 93,
                            ColorId = 4,
                            ProductId = 8,
                            SizeId = 1
                        },
                        new
                        {
                            ProductEntryId = 94,
                            ColorId = 4,
                            ProductId = 8,
                            SizeId = 2
                        },
                        new
                        {
                            ProductEntryId = 95,
                            ColorId = 4,
                            ProductId = 8,
                            SizeId = 3
                        },
                        new
                        {
                            ProductEntryId = 96,
                            ColorId = 4,
                            ProductId = 8,
                            SizeId = 4
                        },
                        new
                        {
                            ProductEntryId = 97,
                            ColorId = 4,
                            ProductId = 8,
                            SizeId = 5
                        },
                        new
                        {
                            ProductEntryId = 98,
                            ColorId = 4,
                            ProductId = 8,
                            SizeId = 6
                        },
                        new
                        {
                            ProductEntryId = 99,
                            ColorId = 5,
                            ProductId = 8,
                            SizeId = 1
                        },
                        new
                        {
                            ProductEntryId = 100,
                            ColorId = 5,
                            ProductId = 8,
                            SizeId = 2
                        },
                        new
                        {
                            ProductEntryId = 101,
                            ColorId = 5,
                            ProductId = 8,
                            SizeId = 3
                        },
                        new
                        {
                            ProductEntryId = 102,
                            ColorId = 5,
                            ProductId = 8,
                            SizeId = 4
                        },
                        new
                        {
                            ProductEntryId = 103,
                            ColorId = 5,
                            ProductId = 8,
                            SizeId = 5
                        },
                        new
                        {
                            ProductEntryId = 104,
                            ColorId = 5,
                            ProductId = 8,
                            SizeId = 6
                        },
                        new
                        {
                            ProductEntryId = 105,
                            ColorId = 6,
                            ProductId = 8,
                            SizeId = 1
                        },
                        new
                        {
                            ProductEntryId = 106,
                            ColorId = 6,
                            ProductId = 8,
                            SizeId = 2
                        },
                        new
                        {
                            ProductEntryId = 107,
                            ColorId = 6,
                            ProductId = 8,
                            SizeId = 3
                        },
                        new
                        {
                            ProductEntryId = 108,
                            ColorId = 6,
                            ProductId = 8,
                            SizeId = 4
                        },
                        new
                        {
                            ProductEntryId = 109,
                            ColorId = 6,
                            ProductId = 8,
                            SizeId = 5
                        },
                        new
                        {
                            ProductEntryId = 110,
                            ColorId = 6,
                            ProductId = 8,
                            SizeId = 6
                        },
                        new
                        {
                            ProductEntryId = 111,
                            ColorId = 7,
                            ProductId = 8,
                            SizeId = 1
                        },
                        new
                        {
                            ProductEntryId = 112,
                            ColorId = 7,
                            ProductId = 8,
                            SizeId = 2
                        },
                        new
                        {
                            ProductEntryId = 113,
                            ColorId = 7,
                            ProductId = 8,
                            SizeId = 3
                        },
                        new
                        {
                            ProductEntryId = 114,
                            ColorId = 7,
                            ProductId = 8,
                            SizeId = 4
                        },
                        new
                        {
                            ProductEntryId = 115,
                            ColorId = 7,
                            ProductId = 8,
                            SizeId = 5
                        },
                        new
                        {
                            ProductEntryId = 116,
                            ColorId = 7,
                            ProductId = 8,
                            SizeId = 6
                        },
                        new
                        {
                            ProductEntryId = 117,
                            ColorId = 8,
                            ProductId = 8,
                            SizeId = 1
                        },
                        new
                        {
                            ProductEntryId = 118,
                            ColorId = 8,
                            ProductId = 8,
                            SizeId = 2
                        },
                        new
                        {
                            ProductEntryId = 119,
                            ColorId = 8,
                            ProductId = 8,
                            SizeId = 3
                        },
                        new
                        {
                            ProductEntryId = 120,
                            ColorId = 8,
                            ProductId = 8,
                            SizeId = 4
                        },
                        new
                        {
                            ProductEntryId = 121,
                            ColorId = 8,
                            ProductId = 8,
                            SizeId = 5
                        },
                        new
                        {
                            ProductEntryId = 122,
                            ColorId = 8,
                            ProductId = 8,
                            SizeId = 6
                        },
                        new
                        {
                            ProductEntryId = 123,
                            ColorId = 9,
                            ProductId = 8,
                            SizeId = 1
                        },
                        new
                        {
                            ProductEntryId = 124,
                            ColorId = 9,
                            ProductId = 8,
                            SizeId = 2
                        },
                        new
                        {
                            ProductEntryId = 125,
                            ColorId = 9,
                            ProductId = 8,
                            SizeId = 3
                        },
                        new
                        {
                            ProductEntryId = 126,
                            ColorId = 9,
                            ProductId = 8,
                            SizeId = 4
                        },
                        new
                        {
                            ProductEntryId = 127,
                            ColorId = 9,
                            ProductId = 8,
                            SizeId = 5
                        },
                        new
                        {
                            ProductEntryId = 128,
                            ColorId = 9,
                            ProductId = 8,
                            SizeId = 6
                        },
                        new
                        {
                            ProductEntryId = 129,
                            ColorId = 10,
                            ProductId = 8,
                            SizeId = 1
                        },
                        new
                        {
                            ProductEntryId = 130,
                            ColorId = 10,
                            ProductId = 8,
                            SizeId = 2
                        },
                        new
                        {
                            ProductEntryId = 131,
                            ColorId = 10,
                            ProductId = 8,
                            SizeId = 3
                        },
                        new
                        {
                            ProductEntryId = 132,
                            ColorId = 10,
                            ProductId = 8,
                            SizeId = 4
                        },
                        new
                        {
                            ProductEntryId = 133,
                            ColorId = 10,
                            ProductId = 8,
                            SizeId = 5
                        },
                        new
                        {
                            ProductEntryId = 134,
                            ColorId = 10,
                            ProductId = 8,
                            SizeId = 6
                        },
                        new
                        {
                            ProductEntryId = 135,
                            ColorId = 11,
                            ProductId = 8,
                            SizeId = 1
                        },
                        new
                        {
                            ProductEntryId = 136,
                            ColorId = 11,
                            ProductId = 8,
                            SizeId = 2
                        },
                        new
                        {
                            ProductEntryId = 137,
                            ColorId = 11,
                            ProductId = 8,
                            SizeId = 3
                        },
                        new
                        {
                            ProductEntryId = 138,
                            ColorId = 11,
                            ProductId = 8,
                            SizeId = 4
                        },
                        new
                        {
                            ProductEntryId = 139,
                            ColorId = 11,
                            ProductId = 8,
                            SizeId = 5
                        },
                        new
                        {
                            ProductEntryId = 140,
                            ColorId = 11,
                            ProductId = 8,
                            SizeId = 6
                        },
                        new
                        {
                            ProductEntryId = 141,
                            ColorId = 11,
                            ProductId = 9,
                            SizeId = 7
                        },
                        new
                        {
                            ProductEntryId = 142,
                            ColorId = 11,
                            ProductId = 9,
                            SizeId = 8
                        },
                        new
                        {
                            ProductEntryId = 143,
                            ColorId = 11,
                            ProductId = 9,
                            SizeId = 9
                        },
                        new
                        {
                            ProductEntryId = 144,
                            ColorId = 11,
                            ProductId = 9,
                            SizeId = 10
                        },
                        new
                        {
                            ProductEntryId = 145,
                            ColorId = 11,
                            ProductId = 9,
                            SizeId = 11
                        },
                        new
                        {
                            ProductEntryId = 146,
                            ColorId = 11,
                            ProductId = 9,
                            SizeId = 12
                        },
                        new
                        {
                            ProductEntryId = 147,
                            ColorId = 11,
                            ProductId = 9,
                            SizeId = 13
                        },
                        new
                        {
                            ProductEntryId = 148,
                            ColorId = 11,
                            ProductId = 9,
                            SizeId = 14
                        });
                });

            modelBuilder.Entity("Projektgrupp4.Models.Entities.ReviewEntity", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Projektgrupp4.Models.Entities.SizeEntity", b =>
                {
                    b.Property<int>("SizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SizeId"));

                    b.Property<string>("SizeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SizeId");

                    b.ToTable("Sizes");

                    b.HasData(
                        new
                        {
                            SizeId = 1,
                            SizeName = "XS"
                        },
                        new
                        {
                            SizeId = 2,
                            SizeName = "S"
                        },
                        new
                        {
                            SizeId = 3,
                            SizeName = "M"
                        },
                        new
                        {
                            SizeId = 4,
                            SizeName = "L"
                        },
                        new
                        {
                            SizeId = 5,
                            SizeName = "XL"
                        },
                        new
                        {
                            SizeId = 6,
                            SizeName = "XXL"
                        },
                        new
                        {
                            SizeId = 7,
                            SizeName = "37"
                        },
                        new
                        {
                            SizeId = 8,
                            SizeName = "38"
                        },
                        new
                        {
                            SizeId = 9,
                            SizeName = "39"
                        },
                        new
                        {
                            SizeId = 10,
                            SizeName = "40"
                        },
                        new
                        {
                            SizeId = 11,
                            SizeName = "41"
                        },
                        new
                        {
                            SizeId = 12,
                            SizeName = "42"
                        },
                        new
                        {
                            SizeId = 13,
                            SizeName = "43"
                        },
                        new
                        {
                            SizeId = 14,
                            SizeName = "44"
                        });
                });

            modelBuilder.Entity("Projektgrupp4.Models.Entities.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AddressEntityUserEntity", b =>
                {
                    b.HasOne("Projektgrupp4.Models.Entities.AddressEntity", null)
                        .WithMany()
                        .HasForeignKey("UserAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projektgrupp4.Models.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Projektgrupp4.Models.Entities.ProductCategoriesEntity", b =>
                {
                    b.HasOne("Projektgrupp4.Models.Entities.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projektgrupp4.Models.Entities.ProductEntity", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Projektgrupp4.Models.Entities.ProductItemEntity", b =>
                {
                    b.HasOne("Projektgrupp4.Models.Entities.ColorEntity", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projektgrupp4.Models.Entities.ProductEntity", "Product")
                        .WithMany("ProductEntries")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projektgrupp4.Models.Entities.SizeEntity", "Size")
                        .WithMany()
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Product");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("Projektgrupp4.Models.Entities.ReviewEntity", b =>
                {
                    b.HasOne("Projektgrupp4.Models.Entities.ProductEntity", "Product")
                        .WithMany("ProductReviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Projektgrupp4.Models.Entities.ProductEntity", b =>
                {
                    b.Navigation("ProductCategories");

                    b.Navigation("ProductEntries");

                    b.Navigation("ProductReviews");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Projektgrupp4.Models.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Projektgrupp4.Models.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projektgrupp4.Models.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Projektgrupp4.Models.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
